= GR8 CRM - Course Management User Interface Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM Course Management User Interface Plugin
:keywords: groovy, grails, crm, gr8crm, documentation, event, course, training, conference
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/technipelago/grails-crm-training-ui
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer Relationship Management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

== Course Management User Interface Plugin

This plugin provide user interfaces for managing events (courses, trainings, conferences, meetings, etc.) in {gr8crm} applications.
It depends on the +crm-training+ plugin for low level services and persistence.

With this plugin you get a basic *CRUD* controller where you can create new, search for and update existing events.

== Changes

2.4.2:: Add export feature and include 'number' column in list of events
2.4.1:: Added training presentation preview and some more UI tweaks.
2.4.0:: First public release

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}

== Contributing

Please report {gr8source}/issues[issues or suggestions].

Want to improve the plugin: Fork the {gr8source}[repository] and send a pull request.
